version: 2.1
jobs:
  build:
    orbs:
      node: circleci/node@2.0.0
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: ./node_modules/.bin/ng build --prod
      - run:
          command: npm install --save-dev firebase-tools
      - run:
          command: ./node_modules/.bin/firebase use coronavirusinfo-app
      - run:
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  workflow:
    jobs:
      - build
