version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: ./node_modules/.bin/ng build --prod
      - run:
          command: npm install --save-dev firebase-tools
      - run:
          command: ./node_modules/.bin/firebase use coronavirusinfo-app
      - run:
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  workflow:
    jobs:
      - build
