version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: curl https://covid19.isciii.es/resources/serie_historica_acumulados.csv > ./src/assets/csv/covid.csv
      - run:
          command: ./node_modules/.bin/ng build --prod
      - run:
          command: npm install --save-dev firebase-tools
      - run:
          command: ./node_modules/.bin/firebase use coronavirusinfo-app
      - run:
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  workflow:
    jobs:
      - build