version: 2.1
orbs:
  node: circleci/node:13.8.0
jobs:
  build-and-deploy:
    executor:
      name: node/default 
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: ./node_modules/.bin/ng build --prod
            - run: npm install --save-dev firebase-tools
            - run: ./node_modules/.bin/firebase use coronavirusinfo-app
            - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
